site_name: Flowify - No code UI for Argo Workflow
theme:
  name: material
  features:
    - navigation.instant
    - navigation.tabs
extra_css:
  - stylesheets/extra.css
repo_url: https://github.com/equinor/flowify-workflows-server
nav:
  - Home: index.md
  - Getting started: 
    - Prerequisites: getting_started.md
    - Local install: run_local.md
    - Deployment: run_k8s.md
    - Access control: 
      - Authentication and Authorization: auth.md
      - Setting up roles: roles.md
  - User Guide:
    - Concepts: concepts.md
    - Workspaces: workspaces.md
    - Components:
      - Concept: components.md
      - Graph: graphs.md
      - Bricks: bricks.md
    - Workflows:
      - Concept: workflows.md
      - Parallel tasks: map.md
      - If/else: if.md
    - Jobs: jobs.md
    - Secrets: secrets.md
    - Volume mount: mounts.md
  - Developer Guide:
    - Setup: dev_env.md
    - Architecture: arch.md
    - Add OIDC provider: oidc.md
  - About: about.md