
name: Build user doc

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: npm install
      uses: actions/setup-node@v3
      with:
        node-version: 16
    - run: |
        wget --quiet https://github.com/gohugoio/hugo/releases/download/v0.81.0/hugo_extended_0.81.0_Linux-64bit.tar.gz
        tar -xvf hugo_extended_0.81.0_Linux-64bit.tar.gz
        npm install --prefix site site
        sudo ./hugo -s=site -d=dest
        rm -r -f ./docs
        cp -r ./site/dest ./docs
    - run: |
        cd docs
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add .
        git commit -m "Build new doc"
        git push
